# export THROTTLING_CPUSET="--cpuset-cpus=$CPUSET"
# export THROTTLING_CPUS="--cpus=$CPUFRAC"
# export THROTTLING_MEM="--memory=$MEM"; export THROTTLING_SWAP="--memory-swap=-1"; export THROTTLING_OOM="--oom-kill-disable"
# export THROTTLING_READ_IOPS="--device-read-iops=/dev/sda:$IOPSR"
# export THROTTLING_WRITE_IOPS="--device-write-iops=/dev/sda:$IOPSW"
# export THROTTLING_READ_BPS="--device-read-bps=/dev/sda:$BPSR"
# export THROTTLING_WRITE_BPS="--device-write-bps=/dev/sda:$BPSW"
